# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: nodeversion
  value: '11.15.x' # '10.x' 

jobs:

# - job: 'MS_Hosted'
#   displayName: 'MS-Hosted'
#   strategy:
#     matrix:
#       'Linux Node16':
#         imageName: 'ubuntu-latest'
#       'Mac Node16':
#         imageName: 'macOS-latest'
#       'Windows Node16':
#         imageName: 'windows-latest'
#       'Linux Node10':
#         imageName: 'ubuntu-latest'
#         AGENT_USE_NODE10: 'true'
#       'Mac Node10':
#         imageName: 'macOS-latest'
#         AGENT_USE_NODE10: 'true'
#       'Windows Node10':
#         imageName: 'windows-latest'
#         AGENT_USE_NODE10: 'true'

#   steps:
#   - task: NodeTool@0
#     inputs:
#       versionSpec: ${{ variables.nodeversion }}
#     displayName: 'Install Node.js'

#   - script: |
#       npm install
#     displayName: 'npm install'


- job: 'Self_Hosted'
  displayName: 'Self-Hosted'
  strategy:
    matrix:
      'Node16':
        AGENT_USE_NODE10: 'false'
      'Node10':
        AGENT_USE_NODE10: 'true'
  pool: Default

  steps:
  - task: NodeTool@0 #.220.1
    inputs:
      versionSpec: ${{ variables.nodeversion }}
    displayName: 'Install Node.js'

  # - task: NodeTool@0.218.0
  #   inputs:
  #     versionSpec: ${{ variables.nodeversion }}
  #   displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'
