# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: nodeversion
  value: '10.x' # '16.10.x'

jobs:

- job: 'MS_Hosted'
  displayName: 'MS-Hosted'
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macOS-latest'
      windows:
        imageName: 'windows-latest'
      linuxnode10:
        imageName: 'ubuntu-latest'
        AGENT_USE_NODE10: 'true'
      macnode10:
        imageName: 'macOS-latest'
        AGENT_USE_NODE10: 'true'
      windowsnode10:
        imageName: 'windows-latest'
        AGENT_USE_NODE10: 'true'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ variables.nodeversion }}
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'



- job: 'Self_Hosted'
  displayName: 'Self-Hosted'
  strategy:
    matrix:
      'Node16':
        AGENT_USE_NODE10: 'false'
      'Node10':
        AGENT_USE_NODE10: 'true'
  pool: Default

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ variables.nodeversion }}
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'